{%set name = "PySocks" %}
{%set version = "1.6.6" %}
{%set compress_type= "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "02419a225ff5dcfc3c9695ef8fc9b4d8cc99658e650c6d4718d4c8f451e63f41" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - socks

about:
  home: https://github.com/Anorov/PySocks
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'A Python SOCKS client module. See https://github.com/Anorov/PySocks for more information.'
  license_family: BSD
  doc_url: https://github.com/Anorov/PySocks/blob/master/README.md
  dev_url: https://github.com/Anorov/PySocks

extra:
  recipe-maintainers:
    - pmlandwehr
