travis:
  secure:
    BINSTAR_TOKEN: KpCRhJT83qg943q+rNLrF43cGH41hPgnoC96mMXBoI0eItsgwjZPzwVKjFBv4fqFRu+ADm/R8B4Ytpi9yqB3/Ryaqc2dAJcTXzCyiV6/kRNQI/7AXYaQCuhll7yGamnVMkKa7n1iNWO34z8cKYehQak396Pngi+i/D+TSxjITis+qkt4WkvGDjkQg1oRXWfkpEprDKTEUyvILzTaOvAlWtg7rN+51qKGJvOBexHqFrxBLYJih2wptjQYAF6g7+e5lTgsBiWFbt0RQH9Fbfi2/zWZybZQAmCE76ck7n1spHPTjTL+7KnIKn2ZWQQbvLnT94lkRRusBI5dOsEY8gso6/rIGs6G24+QJFV2C1WBNgT1VV9yXsHhdqSrYPQ3rlNRG1Yib2GLj/OJxqx8MgYF8AJbwWUsdY1yTz1QZkkjlWic94JrCvjMaF03VdFK9ZTOqe8CJo3PPZBWd8GbNRvRYQwMKS6dBEcWZKNxOG9ydlLuTgrZygdoMTacvR8b7Q/BQFBLdLrZYHd6zbfcMhBpkAR9HvWGl7yX5CUH1kHqeMAy+49GLzJvO1pkkD5xKwlo+n/xPzprpn9f26dlQbc66z5LmFCSOZny2Jk4BVN8pzn9/5JqB4RbyjUV+1RD8q6HT66q88wrxNPNsXE/yrOavgWKNKnYzAzZQBPAH6fypxQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
